$CF = Join-Path -Path ([Environment]::GetFolderPath("UserProfile")) -ChildPath "AppData\Local\OzoneSoft\Context Free\ContextFreeCLI.exe"

& $CF /s1000 "designs/circuitroadmap.cfdg" "renders/circuitroadmap.png"
& $CF /s1000 "designs/combustion.cfdg" "renders/combustion.png"
& $CF /s1000 "designs/controlpoints.cfdg" "renders/controlpoints.png"
& $CF /s1000 "designs/cylindercity.cfdg" "renders/cylindercity.png"
& $CF /s1000 "designs/davinciscrapbook.cfdg" "renders/davinciscrapbook.png"
& $CF /s1000 "designs/dbmeter.cfdg" "renders/dbmeter.png"
& $CF /s1000 "designs/dottedtree.cfdg" "renders/dottedtree.png"
& $CF /s1000 "designs/drafts.cfdg" "renders/drafts.png"
& $CF /s1000 "designs/evolution.cfdg" "renders/evolution.png"
& $CF /s1000 "designs/evolution2.cfdg" "renders/evolution2.png"
& $CF /s1000 "designs/exeunt.cfdg" "renders/exeunt.png"
& $CF /s1000 "designs/isoblocks.cfdg" "renders/isoblocks.png"
& $CF /s1000 "designs/lure.cfdg" "renders/lure.png"
& $CF /s1000 "designs/neurons.cfdg" "renders/neurons.png"
& $CF /s1000 "designs/spidersweb.cfdg" "renders/spidersweb.png"
& $CF /s1000 "designs/tentacletree.cfdg" "renders/tentacletree.png"
& $CF /s1000 "designs/thorns.cfdg" "renders/thorns.png"
& $CF /s1000 "designs/usbtree.cfdg" "renders/usbtree.png"
& $CF /s1000 "designs/veins.cfdg" "renders/veins.png"
& $CF /s1000 "designs/veinsii.cfdg" "renders/veinsii.png"
